/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class Carros extends javax.swing.JInternalFrame {

    PreparedStatement ps;
    ResultSet rs;
    Conexion conC = new Conexion();
    
    public void limpiar(){
        txt_NSerieCarro.setText("");
        txt_marca.setText("");
        txt_linea.setText("");
        txt_kilometraje.setText("");
        txt_modeloCarro.setText("");
        txt_anioCarro.setYear(2022);
        txt_descripcionCarro.setText("");
    }
    
    /**
     * Creates new form Carros
     */
    public Carros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_NSerieCarro = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_linea = new javax.swing.JTextField();
        txt_kilometraje = new javax.swing.JTextField();
        txt_modeloCarro = new javax.swing.JTextField();
        txt_anioCarro = new com.toedter.calendar.JYearChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcionCarro = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Carros");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setText("Numero de Serie:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Linea:");

        jLabel4.setText("Kilometraje:");

        jLabel5.setText("Modelo:");

        jLabel6.setText("Año:");

        jLabel7.setText("Descripción:");

        txt_NSerieCarro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NSerieCarroKeyTyped(evt);
            }
        });

        txt_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_marcaKeyTyped(evt);
            }
        });

        txt_linea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lineaKeyTyped(evt);
            }
        });

        txt_kilometraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kilometrajeKeyTyped(evt);
            }
        });

        txt_modeloCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modeloCarroActionPerformed(evt);
            }
        });
        txt_modeloCarro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_modeloCarroKeyTyped(evt);
            }
        });

        txt_descripcionCarro.setColumns(20);
        txt_descripcionCarro.setRows(5);
        jScrollPane1.setViewportView(txt_descripcionCarro);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButton2)
                .addGap(185, 185, 185)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(110, 110, 110)
                .addComponent(jButton5)
                .addGap(131, 131, 131))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_NSerieCarro)
                    .addComponent(txt_marca)
                    .addComponent(txt_linea)
                    .addComponent(txt_kilometraje)
                    .addComponent(txt_modeloCarro)
                    .addComponent(txt_anioCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_NSerieCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_modeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(txt_anioCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1013, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NSerieCarroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NSerieCarroKeyTyped
        if (txt_NSerieCarro.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_NSerieCarroKeyTyped

    private void txt_marcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_marcaKeyTyped
        if (txt_marca.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_marcaKeyTyped

    private void txt_lineaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lineaKeyTyped
        if (txt_linea.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_lineaKeyTyped

    private void txt_kilometrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kilometrajeKeyTyped
        if (txt_kilometraje.getText().length() >= 8) {
            evt.consume();
        }

        if (Character.isLetter(evt.getKeyChar())) {
            evt.consume();
        } else {
            try {
                Double.parseDouble(txt_kilometraje.getText() + evt.getKeyChar());
            } catch (Exception e) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_kilometrajeKeyTyped

    private void txt_modeloCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modeloCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_modeloCarroActionPerformed

    private void txt_modeloCarroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_modeloCarroKeyTyped
        if (txt_modeloCarro.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_modeloCarroKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txt_NSerieCarro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un indice :/", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;

            try {

                con = conC.getConnection();
                ps = con.prepareStatement("SELECT * FROM carro WHERE num_serie = ?");
                ps.setString(1, txt_NSerieCarro.getText());

                rs = ps.executeQuery();

                if (rs.next()) {

                    txt_marca.setText(rs.getString("marca"));
                    txt_linea.setText(rs.getString("linea"));
                    txt_kilometraje.setText(rs.getString("kilometraje"));
                    txt_modeloCarro.setText(rs.getString("modelo"));
                    txt_anioCarro.setYear(rs.getInt("anio"));
                    txt_descripcionCarro.setText(rs.getString("descripcion"));

                } else {
                    JOptionPane.showMessageDialog(null, "No existe un Carro con el Numero de Serie", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txt_anioCarro.getYear() <= 1950) {
            JOptionPane.showMessageDialog(null, "El año no es valido!", "Hey!", JOptionPane.ERROR_MESSAGE);
        } else if (txt_NSerieCarro.getText().isEmpty() || txt_marca.getText().isEmpty() || txt_linea.getText().isEmpty()
            || txt_kilometraje.getText().isEmpty() || txt_modeloCarro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan algunos Datos!", "Hey!", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;
            try {
                con = conC.getConnection();
                ps = con.prepareStatement("INSERT INTO carro VALUES (?,?,?,?,?,?,?)");
                ps.setString(1, txt_NSerieCarro.getText().trim());
                ps.setString(2, txt_marca.getText().trim());
                ps.setString(3, txt_linea.getText().trim());
                ps.setString(4, txt_kilometraje.getText().trim());
                ps.setString(5, txt_modeloCarro.getText().trim());
                ps.setInt(6, txt_anioCarro.getYear());
                ps.setString(7, txt_descripcionCarro.getText());

                int res = ps.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Carro Guardado Correctamente");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Carro NO Guardado", "Error", JOptionPane.ERROR_MESSAGE);
                }

                con.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txt_NSerieCarro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un Numero de Serie", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;

            try {
                con = conC.getConnection();

                ps = con.prepareStatement("DELETE FROM carro WHERE num_serie = ?");
                ps.setString(1, txt_NSerieCarro.getText());

                int res = ps.executeUpdate();

                if (res > 0) {

                    JOptionPane.showMessageDialog(null, "Carro Eliminado");
                    limpiar();

                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar el Carro", "Error", JOptionPane.ERROR_MESSAGE);
                }
                con.close();

            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (txt_anioCarro.getYear() <= 1950) {
            JOptionPane.showMessageDialog(null, "El año no es valido!", "Hey!", JOptionPane.ERROR_MESSAGE);
        } else if (txt_NSerieCarro.getText().isEmpty() || txt_marca.getText().isEmpty() || txt_linea.getText().isEmpty()
            || txt_kilometraje.getText().isEmpty() || txt_modeloCarro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;

            try {

                con = conC.getConnection();

                ps = con.prepareStatement("UPDATE carro SET marca = ?, linea = ?, kilometraje = ?, modelo = ?, anio = ?, descripcion = ? WHERE num_serie = ?");

                ps.setString(1, txt_marca.getText());
                ps.setString(2, txt_linea.getText());
                ps.setString(3, txt_kilometraje.getText());
                ps.setString(4, txt_modeloCarro.getText());
                ps.setInt(5, txt_anioCarro.getYear());
                ps.setString(6, txt_descripcionCarro.getText());
                ps.setString(7, txt_NSerieCarro.getText());

                int res = ps.executeUpdate();

                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Datos del Carro modificados");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error Al modificar los datos del Carro", "Error", JOptionPane.ERROR_MESSAGE);
                }
                con.close();
            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_NSerieCarro;
    private com.toedter.calendar.JYearChooser txt_anioCarro;
    private javax.swing.JTextArea txt_descripcionCarro;
    private javax.swing.JTextField txt_kilometraje;
    private javax.swing.JTextField txt_linea;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modeloCarro;
    // End of variables declaration//GEN-END:variables
}
