/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class Piezas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Piezas
     */
    public Piezas() {
        initComponents();
    }
    PreparedStatement ps;
    ResultSet rs;
    Conexion conC = new Conexion();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        txt_precio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_garantia = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_NPiezaPieza = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_descripcionPieza = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        txt_NumeroSeriePieza = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cb_estado = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Piezas");

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel8.setText("Garantia:");

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });

        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txt_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_precioKeyTyped(evt);
            }
        });

        jLabel9.setText("Numero de pieza:");

        txt_garantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_garantiaActionPerformed(evt);
            }
        });
        txt_garantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_garantiaKeyTyped(evt);
            }
        });

        jButton7.setText("Guardar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel10.setText("Numero de Serie:");

        jLabel11.setText("Descripción:");

        jButton8.setText("Eliminar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel12.setText("Nombre:");

        txt_NPiezaPieza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NPiezaPiezaKeyTyped(evt);
            }
        });

        txt_descripcionPieza.setColumns(20);
        txt_descripcionPieza.setRows(5);
        txt_descripcionPieza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_descripcionPiezaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txt_descripcionPieza);

        jButton9.setText("Actualizar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        txt_NumeroSeriePieza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NumeroSeriePiezaKeyTyped(evt);
            }
        });

        jLabel13.setText("Precio:");

        jButton10.setText("Limpiar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel1.setText("Status:");

        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "0", "1", "2" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_NPiezaPieza)
                            .addComponent(txt_NumeroSeriePieza)
                            .addComponent(txt_nombre)
                            .addComponent(txt_precio)
                            .addComponent(txt_garantia)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(cb_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton7)
                        .addGap(185, 185, 185)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                        .addComponent(jButton9)))
                .addGap(110, 110, 110)
                .addComponent(jButton10)
                .addGap(131, 131, 131))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_NPiezaPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_NumeroSeriePieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_garantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton9)
                    .addComponent(jButton8)
                    .addComponent(jButton7))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1013, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        if (txt_nombre.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (txt_NPiezaPieza.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un indice :/", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;

            try {

                con = conC.getConnection();
                ps = con.prepareStatement("SELECT * FROM pieza WHERE num_pieza = ?");
                ps.setString(1, txt_NPiezaPieza.getText());

                rs = ps.executeQuery();

                if (rs.next()) {

                    txt_NumeroSeriePieza.setText(rs.getString("num_serie"));
                    txt_nombre.setText(rs.getString("nombre"));
                    txt_precio.setText(rs.getString("precio_minimo"));
                    txt_garantia.setText(rs.getString("garantia"));
                    txt_descripcionPieza.setText(rs.getString("descripcion"));
                    cb_estado.setSelectedItem(rs.getString("estado"));

                } else {
                    JOptionPane.showMessageDialog(null, "No existe una Pieza con ese Numero de Pieza", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precioKeyTyped
        if (txt_precio.getText().length() >= 8) {
            evt.consume();
        }

        if (Character.isLetter(evt.getKeyChar())) {
            evt.consume();
        } else {
            try {
                Double.parseDouble(txt_precio.getText() + evt.getKeyChar());
            } catch (Exception e) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_precioKeyTyped

    private void txt_garantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_garantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_garantiaActionPerformed

    private void txt_garantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_garantiaKeyTyped
        if (txt_garantia.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_garantiaKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (txt_NPiezaPieza.getText().isEmpty() || txt_NumeroSeriePieza.getText().isEmpty() || txt_nombre.getText().isEmpty()
            || txt_precio.getText().isEmpty() || txt_garantia.getText().isEmpty() || txt_descripcionPieza.getText().isEmpty()
                || "Seleccione".equals(cb_estado.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Faltan algunos Datos!", "Hey!", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;
            try {
                con = conC.getConnection();
                ps = con.prepareStatement("INSERT INTO pieza VALUES (?,?,?,?,?,?)");
                ps.setString(1, txt_NPiezaPieza.getText().trim());
                ps.setString(2, txt_NumeroSeriePieza.getText().trim());
                ps.setString(3, txt_nombre.getText().trim());
                ps.setString(4, txt_precio.getText().trim());
                ps.setString(5, txt_garantia.getText().trim());
                ps.setString(6, txt_descripcionPieza.getText());

                int res = ps.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Pieza Guardada Correctamente");
                    limpiarPieza();
                } else {
                    JOptionPane.showMessageDialog(null, "Pieza NO Guardada", "Error", JOptionPane.ERROR_MESSAGE);
                }

                con.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (txt_NPiezaPieza.getText().isEmpty() || txt_NumeroSeriePieza.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un Numero de Pieza", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;

            try {
                con = conC.getConnection();

                ps = con.prepareStatement("DELETE FROM pieza WHERE num_pieza = ? AND num_serie= ?");
                ps.setString(1, txt_NPiezaPieza.getText());
                ps.setString(2, txt_NumeroSeriePieza.getText());

                int res = ps.executeUpdate();

                if (res > 0) {

                    JOptionPane.showMessageDialog(null, "Pieza Eliminada");
                    limpiarPieza();

                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar la Pieza", "Error", JOptionPane.ERROR_MESSAGE);
                }
                con.close();

            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txt_NPiezaPiezaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NPiezaPiezaKeyTyped
        if (txt_NPiezaPieza.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_NPiezaPiezaKeyTyped

    private void txt_descripcionPiezaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionPiezaKeyTyped
        if (txt_NumeroSeriePieza.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_descripcionPiezaKeyTyped

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (txt_NPiezaPieza.getText().isEmpty() || txt_NumeroSeriePieza.getText().isEmpty() || txt_nombre.getText().isEmpty()
            || txt_precio.getText().isEmpty() || txt_garantia.getText().isEmpty() || txt_descripcionPieza.getText().isEmpty()
            || "Seleccione".equals(cb_estado.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;

            try {

                con = conC.getConnection();

                ps = con.prepareStatement("UPDATE pieza SET num_serie = ?, nombre  = ?, precio_minimo = ?, garantia = ?, descripcion = ?, estado = ? WHERE num_pieza = ?");

                ps.setString(1, txt_NumeroSeriePieza.getText());
                ps.setString(2, txt_nombre.getText());
                ps.setString(3, txt_precio.getText());
                ps.setString(4, txt_garantia.getText());
                ps.setString(5, txt_descripcionPieza.getText());
                ps.setInt(6, Integer.parseInt((String) cb_estado.getSelectedItem()));
                ps.setString(7, txt_NPiezaPieza.getText());

                int res = ps.executeUpdate();

                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Datos de la Pieza modificados");
                    limpiarPieza();
                } else {
                    JOptionPane.showMessageDialog(null, "Error Al modificar los datos de la Pieza", "Error", JOptionPane.ERROR_MESSAGE);
                }
                con.close();
            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txt_NumeroSeriePiezaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NumeroSeriePiezaKeyTyped
        if (txt_NumeroSeriePieza.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_NumeroSeriePiezaKeyTyped

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        limpiarPieza();
    }//GEN-LAST:event_jButton10ActionPerformed

    void limpiarPieza(){
        txt_NPiezaPieza.setText("");
        txt_NumeroSeriePieza.setText("");
        txt_nombre.setText("");
        txt_precio.setText("");
        txt_garantia.setText("");
        txt_descripcionPieza.setText("");
        cb_estado.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_NPiezaPieza;
    private javax.swing.JTextField txt_NumeroSeriePieza;
    private javax.swing.JTextArea txt_descripcionPieza;
    private javax.swing.JTextField txt_garantia;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
