/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class VentaCRUD extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentaCRUD
     */
    public VentaCRUD() {
        initComponents();
    }

    PreparedStatement ps;
    ResultSet rs;
    Conexion conC = new Conexion();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txt_idVendedorVenta = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        txt_Total = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txt_fechaVenta = new com.toedter.calendar.JDateChooser();
        jButton18 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txt_IDventa = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Venta");

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        txt_idVendedorVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idVendedorVentaKeyTyped(evt);
            }
        });

        jButton16.setText("Buscar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        txt_Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TotalKeyTyped(evt);
            }
        });

        jLabel17.setText("ID venta:");

        jButton17.setText("Guardar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel18.setText("Fecha:");

        jButton18.setText("Eliminar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel19.setText("ID Vendedor:");

        txt_IDventa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IDventaKeyTyped(evt);
            }
        });

        jButton19.setText("Actualizar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel20.setText("Total:");

        jButton20.setText("Limpiar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButton17)
                .addGap(185, 185, 185)
                .addComponent(jButton18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(jButton19)
                .addGap(110, 110, 110)
                .addComponent(jButton20)
                .addGap(131, 131, 131))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_idVendedorVenta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_IDventa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Total)
                    .addComponent(txt_fechaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_IDventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(txt_fechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_idVendedorVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20)
                    .addComponent(jButton19)
                    .addComponent(jButton18)
                    .addComponent(jButton17))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1013, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idVendedorVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idVendedorVentaKeyTyped
        if (txt_idVendedorVenta.getText().length() >= 5) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_idVendedorVentaKeyTyped

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (txt_IDventa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un ID :/", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;

            try {

                con = conC.getConnection();
                ps = con.prepareStatement("SELECT * FROM venta WHERE id_venta = ?");
                ps.setString(1, txt_IDventa.getText());

                rs = ps.executeQuery();

                if (rs.next()) {

                    txt_fechaVenta.setDate(rs.getDate("fecha"));
                    txt_idVendedorVenta.setText(rs.getString("id_vendedor"));
                    txt_Total.setText(rs.getString("total"));

                } else {
                    JOptionPane.showMessageDialog(null, "No existe alguna Venta con ese ID", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void txt_TotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TotalKeyTyped
        if (txt_Total.getText().length() >= 8) {
            evt.consume();
        }

        if (Character.isLetter(evt.getKeyChar())) {
            evt.consume();
        } else {
            try {
                Double.parseDouble(txt_Total.getText() + evt.getKeyChar());
            } catch (Exception e) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_TotalKeyTyped

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        if (txt_IDventa.getText().isEmpty() || txt_fechaVenta.getDate() == null || txt_idVendedorVenta.getText().isEmpty()
            || txt_Total.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan algunos Datos!", "Hey!", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;
            try {
                con = conC.getConnection();
                ps = con.prepareStatement("INSERT INTO venta VALUES (?,?,?,?)");
                ps.setString(1, txt_IDventa.getText().trim());
                ps.setObject(2, txt_fechaVenta.getDate());
                ps.setString(3, txt_idVendedorVenta.getText().trim());
                ps.setString(4, txt_Total.getText().trim());

                int res = ps.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Venta Guardada Correctamente");
                    limpiarVenta();
                } else {
                    JOptionPane.showMessageDialog(null, "Venta NO Guardado", "Error", JOptionPane.ERROR_MESSAGE);
                }

                con.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        if (txt_IDventa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un ID", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;

            try {
                con = conC.getConnection();

                ps = con.prepareStatement("DELETE FROM venta WHERE id_venta = ?");
                ps.setInt(1, Integer.parseInt(txt_IDventa.getText()));

                int res = ps.executeUpdate();

                if (res > 0) {

                    JOptionPane.showMessageDialog(null, "Venta Eliminada");
                    limpiarVenta();

                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar la Venta", "Error", JOptionPane.ERROR_MESSAGE);
                }
                con.close();

            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void txt_IDventaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IDventaKeyTyped
        if (txt_IDventa.getText().length() >= 5) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_IDventaKeyTyped

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        if (txt_IDventa.getText().isEmpty() || txt_fechaVenta.getDate() == null || txt_idVendedorVenta.getText().isEmpty()
            || txt_Total.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;

            try {

                con = conC.getConnection();

                ps = con.prepareStatement("UPDATE venta SET fecha = ?, id_vendedor = ?, total = ? WHERE id_venta = ?");

                ps.setObject(1, txt_fechaVenta.getDate());
                ps.setString(2, txt_idVendedorVenta.getText());
                ps.setString(3, txt_Total.getText());
                ps.setString(4, txt_IDventa.getText());

                int res = ps.executeUpdate();

                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Datos de la Venta modificados");
                    limpiarVenta();
                } else {
                    JOptionPane.showMessageDialog(null, "Error Al modificar los datos de la Venta", "Error", JOptionPane.ERROR_MESSAGE);
                }
                con.close();
            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        limpiarVenta();
    }//GEN-LAST:event_jButton20ActionPerformed

    public void limpiarVenta(){
        txt_IDventa.setText("");
        txt_fechaVenta.setDate(null);
        txt_idVendedorVenta.setText("");
        txt_Total.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_IDventa;
    private javax.swing.JTextField txt_Total;
    private com.toedter.calendar.JDateChooser txt_fechaVenta;
    private javax.swing.JTextField txt_idVendedorVenta;
    // End of variables declaration//GEN-END:variables
}
